twig:
    paths:
        '%kernel.project_dir%/src/Infrastructure/Users/Http/Resources/views': 'users'
        '%kernel.project_dir%/src/Infrastructure/Shared/Templates': ~
    globals:
        app_version: '%env(APP_VERSION)%'
        


# twig:
#     default_path: '%kernel.project_dir%/templates'

# when@test:
#     twig:
#         strict_variables: true
