twig:
    paths:
        '%kernel.project_dir%/src/Infrastructure/Http/Resources/views': views
    globals:
        app_version: '%env(APP_VERSION)%'


# twig:
#     default_path: '%kernel.project_dir%/templates'

# when@test:
#     twig:
#         strict_variables: true
