# controllers:
#     resource:
#         path: ../src/Infrastructure/
#         namespace: App\Infrastructure
#         exclude: 
#             - '../src/Infrastructure/*/Persistence/'
#             - '../src/Infrastructure/Shared/Persistence/'
#     type: attribute

controllers:
    resource:  '../src/Infrastructure/**/Http/Controllers/*Controller.php'
    type: attribute