parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false  # Por defecto privado, mejor para performance

    # 1. CARGA PRINCIPAL - Todo App, con excludes inteligentes
    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/*/Model/'
            - '../src/Domain/*/ValueObject/'
            - '../src/Infrastructure/*/Persistence/Doctrine/Entity/'
            - '../src/Infrastructure/*/Persistence/Doctrine/Mapping/'
            - '../src/Kernel.php'
            - '../src/Tests/'


    # 2. CONTROLLERS - Ahora en Infrastructure/[Dominio]/Controller/
    # Opción A: Si TODOS tus controllers extienden AbstractController (recomendado)
    _instanceof:
        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            tags: ['controller.service_arguments']
            public: true

    # 3. BINDINGS DE INTERFACES (solo los necesarios)
    App\Domain\Users\Repository\UserRepositoryInterface: 
        '@App\Infrastructure\Users\Persistence\UserRepository'
    
    # 4. SERVICIOS ESPECÍFICOS que necesitan configuración especial
    App\Application\Users\UseCase\Register\RegisterUseCase:
        public: true  # Solo si realmente necesita ser público (para tests)